volumes:
  nodemodules: {}
  postgres_data:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  webapp:
    container_name: devsoft-frontend
    build:
      context: .
      dockerfile: ./docker/Dockerfile-frontend
    tty: true
    networks:
      - frontend
    ports:
      - "0.0.0.0:8080:4200"
    volumes:
      - nodemodules:/node_modules
    entrypoint: ["nx", "serve", "frontend", "--host", "0.0.0.0"]

  webapi:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile-backend
    tty: true
    networks:
      - backend
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      NODE_ENV: development

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: '1234'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data







