FROM node:alpine AS build

WORKDIR /app

COPY ./package* .

RUN npm install

COPY . .

RUN npm install nx@latest --global

RUN rm -rf ./node_modules/.cache/nx

EXPOSE 3000

ENTRYPOINT ["node", "dist/apps/backend/main.js"]
